# This is a basic workflow to help you get started with Actions

name: Provision Azure Resources

on:
  workflow_dispatch:
    inputs:
      resource_group_name:
        description: 'Azure Resource Group for resources'
        required: true
      region_name:
        description: 'Azure Region for resources'
        required: true
      registry:
        description: 'Container Registry for Images (Bot Docker Image)'
        required: true
      app_name:
        description: 'Web App for Containers (Bot Host) and App Service Plan (Linux)'
        required: true
      keyvault_name:
        description: 'KeyVault to hold Registry details'
        required: true

jobs:
  provision:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to Azure
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZ_VSE_PR }}

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
