# This is a basic workflow to help you get started with Actions

name: Provision Azure Resources

on:
  workflow_dispatch:
    inputs:
      resource_group_name:
        description: 'Azure Resource Group for resources'
        required: true
      region_name:
        description: 'Azure Region for resources'
        required: true
      registry:
        description: 'Container Registry for Images (Bot Docker Image)'
        required: true
      app_name:
        description: 'Web App for Containers (Bot Host) and App Service Plan (Linux)'
        required: true
      keyvault_name:
        description: 'KeyVault to hold Registry details'
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
